### ISSUE TITLE
Animate fish's tail

### ISSUE THREAD

**Issue by lrq3000** [lrq3000/wikipedia-fr-aprils-fools#1]
If anyone knows how to do animated ASCII art, please help in making the fish's tail animated, I think the effect would be awesome! :-)

**Comment by Lofhi** [comment]
#3 devrait faire l'affaire ? C'est simple et normalement c'est supporter par tous les nivagateurs.
Voir [CSS3 2D Transforms](https://caniuse.com/#feat=transforms2d).

**Comment by lrq3000** [comment]
Oui c'est parfait, merci beaucoup! :D
